export default {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAIL: 'REGISTER_FAIL',
  LOGOUT: 'LOGOUT',

  ADD_TO_CART: 'ADD_TO_CART',
  ADJUST_ITEM_QTY: 'ADJUST_ITEM_QTY',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  LOAD_CURRENT_ITEM: 'LOAD_CURRENT_ITEM',
  ADD_CATEGORY: 'ADD_CATEGORY',
  RESET_CART: 'RESET_CART',
  ADD_ORDER_NAME: 'ADD_ORDER_NAME',
};
