import React, { useState, useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { Navigate, useNavigate } from "react-router-dom";
import CreateOrderModal from "../compnents/CreateOrderModal";
import "../css/Home.css";
import Avatar from "../images/avatar.svg";
import constants from "../redux/constants";
import axiosInstance from "../utils/axios";

const Home = () => {
	const [modalVisible, setModalVisible] = useState(false);
	const [loading, setLoading] = useState(false);
	const [orders, setOrders] = useState();
	const dispatch=useDispatch();
	const navigate=useNavigate();

	const token = useSelector((state) => state.auth.userData.token);

	useEffect(() => {
		async function getOrders() {
			setLoading(true);
			await axiosInstance
				.get("/orders/?page=1", {}, {})
				.then((res) => {
					setLoading(false);
					setOrders(res.data.data);
				})
				.catch((err) => console.log(err));
		}
		getOrders();
	}, []);

	const handleOrderAccept = async (orderDetails) => {
		await axiosInstance
			.put(
				"/orders/" + orderDetails._id + "/accept",
				{},
				{
					headers: {
						Authorization: `Bearer ${token}`,
					},
				}
			)
			.then((res) => {
				console.log(res);
			})
			.catch((err) => console.log(err.response.data));
	};

	return (
		<>
			<div className='home-cont'>
				<div className='navbar' style={{ paddingTop: "20px" }}>
					<div className='nearby'>NEARBY ORDERS</div>
					<div className='nav-right'>
						<div className='create-btn' onClick={() => setModalVisible(true)}>
							Create Order
						</div>
						<div className='logout' onClick={()=>{
							dispatch({type:constants.LOGOUT})
							navigate("/login");
						}}>Log out</div>
					</div>
				</div>
				<div className='home' style={{ marginTop: "20px" }}>
					<div className='table'>
						<div>
							<div className='tab-header'>
								<div className='gen'>GENERATED BY</div>
								<div className='title'>TITLE</div>
								<div className='category'>CATGORY</div>
								<div className='points'>POINTS</div>
								<div className='action'>ACTION</div>
							</div>
							<hr className='divider' />
						</div>
						<div className='table-body'>
							{orders &&
								orders.map((order) => (
									<div key={order}>
										<div className='order-row'>
											<div className='gen'>
												<div>
													<img src={Avatar} alt='avatar' />
												</div>
												<div className='gen-text'>
													{order.generatedBy.username}
												</div>
											</div>
											<div className='title'>{order.name}</div>
											<div className='category'>{order.category}</div>
											<div className='points'>{order.points}</div>
											<div className='action'>
												<div
													className='create-btn'
													onClick={(order) => handleOrderAccept(order)}>
													Accept Order
												</div>
											</div>
										</div>
										<hr className='divider' />
									</div>
								))}
						</div>
					</div>
				</div>
			</div>
			<CreateOrderModal
				modalVisible={modalVisible}
				setModalVisible={setModalVisible}
			/>
		</>
	);
};

export default Home;
